const basePath = process.cwd(),
  { MODE: MODE } = require(`${basePath}/constants/blend_mode.js`),
  { NETWORK: NETWORK } = require(`${basePath}/constants/network.js`),
  network = NETWORK.eth,
  namePrefix = "Peoject Name",
  description = "Des...",
  baseUri = "ipfs://NewUriToReplace",
  solanaMetadata = {
    symbol: "YC",
    seller_fee_basis_points: 1e3,
    external_url: "https://www.youtube.com/c/hashlipsnft",
    creators: [
      { address: "7fXNuer5sbZtaTEPhtJ5g5gNtuyRoKkvxdjEjEnPN4mC", share: 100 },
    ],
  },
  layerConfigurations = [
    {
      growEditionSizeTo: 10,
      layersOrder: [
        { name: "Background" },
        { name: "Eyeball" },
        { name: "Eye color" },
        { name: "Iris" },
        { name: "Shine" },
        { name: "Bottom lid" },
        { name: "Top lid" },
      ],
    },
  ],
  shuffleLayerConfigurations = !1,
  debugLogs = !1,
  format = { width: 512, height: 512, smoothing: !1 },
  gif = { export: !0, repeat: 0, quality: 100, delay: 50 },
  text = {
    only: !1,
    color: "#ffffff",
    size: 20,
    xGap: 40,
    yGap: 40,
    align: "left",
    baseline: "top",
    weight: "regular",
    family: "Courier",
    spacer: " => ",
  },
  pixelFormat = { ratio: 2 / 128 },
  background = {
    generate: !0,
    brightness: "80%",
    static: !1,
    default: "#000000",
  },
  extraMetadata = {},
  rarityDelimiter = "#",
  uniqueDnaTorrance = 1e4,
  preview = {
    thumbPerRow: 5,
    thumbWidth: 50,
    imageRatio: format.height / format.width,
    imageName: "preview.png",
  },
  preview_gif = {
    numberOfImages: 5,
    order: "ASC",
    repeat: 0,
    quality: 100,
    delay: 500,
    imageName: "preview.gif",
  };
module.exports = {
  format: format,
  baseUri: baseUri,
  description: description,
  background: background,
  uniqueDnaTorrance: 1e4,
  layerConfigurations: layerConfigurations,
  rarityDelimiter: "#",
  preview: preview,
  shuffleLayerConfigurations: !1,
  debugLogs: !1,
  extraMetadata: extraMetadata,
  pixelFormat: pixelFormat,
  text: text,
  namePrefix: namePrefix,
  network: network,
  solanaMetadata: solanaMetadata,
  gif: gif,
  preview_gif: preview_gif,
};
